### ISSUE TITLE
How should I tell cpm where it should install?

### ISSUE THREAD

**Issue by nickanderson** [olehermanse/cpm#2]
My workflow involves forking a main repo, cloning my fork locally, branching my fork, pushing my branch to my fork, and finally open a pull request for merging into the main repository.

When I do `cpm install cfengine-lynis` as my normal unprivileged user I get a permission denied error:

```
Permission denied: '/var/cfengine/services'
```

Does `cpm` actually take care of installing files? Currently `cfengine-lynis` contains a `makefile` and that makefile rsyncs from the cloned repository into `$MASTERFILES` which defaults to `/var/cfengine/masterfiles` but can be overridden by setting the `MASTERFILES` environment variable. But it seems odd to do `MASTERFILES=~/CFEngine/masterfiles cpm install cfengine-lynis`

**Comment by olehermanse** [comment]
I think you might like: https://github.com/olehermanse/cpm/commit/4e0e8244b146e6caf419f2bac224bb232be77764

**Comment by olehermanse** [comment]
@nickanderson After that commit, it should prompt you the first time you start `cpm`. Alternatively you can create the config file yourself. In that case, `/user/config.json` should look like this:
```
{
  "cfe": "/var/cfengine/",
  "mpf": "/var/cfengine/masterfiles",
  "import_def_json": "yes",
  "auto_apply": "yes"
}
```

**Comment by nickanderson** [comment]
I updated to master. I deleted the `user` directory inside my clone. I ran cpm. and got an error about usage.

```
> $ cpm                                                                                           [±master]
usage: cpm [-h] [--loglevel LOGLEVEL] cmd [cmd ...]
cpm: error: the following arguments are required: cmd
```

I ran `cpm -h`

```
> $ cpm -h                                                                                        [±master]
usage: cpm [-h] [--loglevel LOGLEVEL] cmd [cmd ...]

CFEngine package manager.

positional arguments:
  cmd                   The command to perform

optional arguments:
  -h, --help            show this help message and exit
  --loglevel LOGLEVEL, -l LOGLEVEL
                        Set log level for more/less detailed output
```

I looked at the code found `cpm search` and ran it. I was prompted  for where CFEngine is installed. I think this is asking about binary locations. I took the default. It asked me where masterfiles was located. I think it means my working policy set. I told it `~/CFEngine/masterfiles`. It told me it didnt exist. So I gave it the fully qualified path and it liked that better. It asked if I wanted to import my existing `def.json` (Augments file). I said yes (even though I don't have one in the directory I specified). It said that after import the def.json is empty. It then asked if I want cpm to automatically apply installed packages to cfengine folders. I said yes because I think this means my working policy set, not the actual system /var/cfengine/masterfiles.

```
> $ cpm search                                                                                    [±master]
Where is CFEngine installed? (Empty for default)

Where is masterfiles located? (Empty for default)
~/CFEngine/masterfiles
Directory '~/CFEngine/masterfiles' does not exist!
Where is masterfiles located? (Empty for default)
/home/nickanderson/CFEngine/masterfiles
Do you want to import your existing def.json file?(y/n) y
Warning: '/home/nickanderson/src/cpm/user/def.json' is empty after import.
This likely means the file did not exist or had no data
Do you want cpm to automatically apply installed packages to CFEngine folders?(y/n) y
cfengine-cis
cfengine-lynis
cfengine-local_users
client_initiated_reporting
```

I ran `cpm install cfengine-lynis` 

```
> $ cpm install cfengine-lynis                                                                    [±master]
Downloading 'cfengine-lynis'...
Installing 'cfengine-lynis'...
make: Entering directory '/home/nickanderson/src/cpm/user/packages/cfengine-lynis'
mkdir -p /var/cfengine/masterfiles/services/cfengine-lynis/
mkdir: cannot create directory ‘/var/cfengine/masterfiles/services’: Permission denied
makefile:6: recipe for target 'install' failed
make: *** [install] Error 1
make: Leaving directory '/home/nickanderson/src/cpm/user/packages/cfengine-lynis'
Finished installer(s) for 'cfengine-lynis'.

```

I can see that the make file is triggering and using the default path for MASTERFILES since the environment variable is not set.

I ran it again and set MASTERFILES to the path to my policy set (matching what I told `cpm`).

```
> $ MASTERFILES=~/CFEngine/masterfiles cpm install cfengine-lynis                                 [±master]
Downloading 'cfengine-lynis'...
Installing 'cfengine-lynis'...
make: Entering directory '/home/nickanderson/src/cpm/user/packages/cfengine-lynis'
mkdir -p /home/nickanderson/CFEngine/masterfiles/services/cfengine-lynis/
rsync -avz --exclude \.#.* /home/nickanderson/src/cpm/user/packages/cfengine-lynis/* /home/nickanderson/CFEngine/masterfiles/services/cfengine-lynis/
sending incremental file list
LICENSE
README.org
def.json
makefile
data/
data/4f/
data/4f/23848e-ef9c-44aa-b268-dafe86ff7979/
data/4f/23848e-ef9c-44aa-b268-dafe86ff7979/2017-10-09_Selection_003_2017-10-09_12-50-52.png
data/4f/23848e-ef9c-44aa-b268-dafe86ff7979/2017-10-09_Selection_003_2017-10-09_14-38-01.png
policy/
policy/main.cf

sent 386,880 bytes  received 173 bytes  774,106.00 bytes/sec
total size is 407,558  speedup is 1.05
find /home/nickanderson/CFEngine/masterfiles/services/cfengine-lynis/ -type f | xargs chmod 600
find /home/nickanderson/CFEngine/masterfiles/services/cfengine-lynis/ -type d | xargs chmod 700
echo "Don't forget to include the policy in inputs!"
Don't forget to include the policy in inputs!
echo "Try the augments file (def.json)"
Try the augments file (def.json)
echo '{"inputs": [ "services/cfengine-lynis/policy/main.cf" ]}'
{"inputs": [ "services/cfengine-lynis/policy/main.cf" ]}
make: Leaving directory '/home/nickanderson/src/cpm/user/packages/cfengine-lynis'
Finished installer(s) for 'cfengine-lynis'.
```

I looked at my directory and see that services/cfengine-lynis exists and contains all the content from my repo. I believe that rsync triggered from my makefile took care of copying these files into place as expected. However my augments file `def.json` is empty when I expected that it would contain entries for inputs and vars to make the policy run by default.

https://github.com/nickanderson/cfengine-lynis/blob/master/def.json

**Comment by olehermanse** [comment]
@nickanderson I added usage instructions to readme.

cpm doesn't use CFEngine binaries. CFEngine install location is where CFEngine is installed. Default: `/var/cfengine`

Masterfiles is path to masterfiles policy framework. Default: `<CFEngine install>/masterfiles` 

"Applying changes to CFEngine folders" means making changes outside of cpm folders, for example running `make` in downloaded packges or overwriting `/var/cfengine/masterfiles/def.json` or similar. cpm has no reservations when it comes to making changes inside cpm folders, but cannot control what package scripts/makefiles do.

`cpm apply` is used to explicitly run installers and overwrite CFEngine files (`def.json`).

**Comment by nickanderson** [comment]
Perhaps when invoking make you could define some environment variables that could be used to adjust install directory?

**Comment by olehermanse** [comment]
@nickanderson Fixed a few things, seems to be working OK for me on centos now:

```
[root@centos-hub ~]# git clone https://github.com/olehermanse/cpm.git
Cloning into 'cpm'...
remote: Counting objects: 112, done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 112 (delta 50), reused 96 (delta 34), pack-reused 0
Receiving objects: 100% (112/112), 37.85 KiB | 14.00 KiB/s, done.
Resolving deltas: 100% (50/50), done.
[root@centos-hub ~]# cpm install cir
Where is CFEngine installed? (Empty for default)

Where is masterfiles located? (Empty for default)

Do you want to import your existing def.json file?(y/n) y
Do you want cpm to automatically apply installed packages to CFEngine folders?(y/n) y
Downloading 'client_initiated_reporting'...
Cloning into 'cfengine_basics'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 1), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
Installing 'client_initiated_reporting'...
Finished installer(s) for 'client_initiated_reporting'.
Successfully applied changes to '/var/cfengine/masterfiles/def.json'
[root@centos-hub ~]# rm /var/cfengine/masterfiles/def.json
rm: remove regular file ‘/var/cfengine/masterfiles/def.json’? y
[root@centos-hub ~]# cd cpm/
[root@centos-hub cpm]# rm user/install/def.json
rm: remove regular file ‘user/install/def.json’? y
[root@centos-hub cpm]# rm user/def.json
rm: remove regular file ‘user/def.json’? y
[root@centos-hub cpm]# cpm install cir
Downloading 'client_initiated_reporting'...
Already up-to-date.
Installing 'client_initiated_reporting'...
Finished installer(s) for 'client_initiated_reporting'.
Successfully applied changes to '/var/cfengine/masterfiles/def.json'
[root@centos-hub cpm]# cat /var/cfengine/masterfiles/def.json
{
  "classes": {
    "client_initiated_reporting_enabled": [
      "any"
    ]
  },
  "vars": {
    "control_hub_exclude_hosts": [
      "0.0.0.0/0"
    ],
    "control_server_call_collect_interval": "1"
  }
}
```

**Comment by olehermanse** [comment]
@nickanderson Using environment variables is a good idea, I created this: https://github.com/olehermanse/cpm/issues/3

Feel free to leave your ideas there, I won't work on it before friday.
